### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by RandomSort** [benhayehudi/portfolio-site-client-3.0#1]
Hi Ben,
nice portfolio site.
You are missing `favicon.ico` which leads to a 404 in my console :)

Have a great day!

**Comment by benhayehudi** [comment]
This has been fixed: https://github.com/benhayehudi/portfolio-site-client-3.0/commit/58f3c1e058919bc934d2b26683e74d9a4a93d59d. Thanks again for raising this!
